version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
  web_server:
    build: ./web_server
    restart: always
    stdin_open: true 
    tty: true 
    # port must be open even in production as it's a webserver open to outside
    # TODO: setup authentication
    environment:
      - APP_USER=cdozen
      - APP_PASSWORD=test
    ports:
      - "8001:8000"
    expose:
      - "8001"
    links:
      - mosquitto
    command: ["uvicorn", "web_server.app_mqtt:app", "--host", "0.0.0.0"]
    volumes:
      - web_server:/code

volumes:
  mosquitto_data:
  mosquitto_log:
  mosquitto.conf:
  web_server:

  
